server:
  host: '127.0.0.1'
  port: 10808
mysql:
  user: ''
  password: ''
  host: '127.0.0.1'
  port: 3306
  dbname:  ''
ldap:
  host: ''
  port: 339
  dn: ''
  password: ''
  user_search: ''
  group_search: ''
